#!/usr/bin/env python3
# rominfo.py -o rominfo.h val1 val2 val3 ...
# generate a header with the rom info string

import sys
import argparse
import os


def gen_rominfo(vals):
  return "rominfo[" + ",".join(vals) + "]"


def write_header(output, rominfo):
  base = os.path.basename(output).upper().replace('.', '_')
  data = """// rominfo - do not edit! autogenerated file!!
#ifndef {0}
#define {0}

#define ROMINFO_STRING "{1}"
#define ROMINFO_SIZE {2}

#endif
  """.format(base, rominfo, len(rominfo))
  with open(output, "w") as fh:
    fh.write(data)


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('vals', nargs='+', help="entries for rominfo")
  parser.add_argument('-o', '--output', help="header output file")
  parser.add_argument('-v', '--verbose', action='store_true', default=False, help="show rominfo")
  args = parser.parse_args()

  rominfo = gen_rominfo(args.vals)
  if args.verbose:
    print(rominfo)
  if args.output:
    write_header(args.output, rominfo)
  return 0


if __name__ == '__main__':
  sys.exit(main())
