#ifndef PARAM_DEF_H
#define PARAM_DEF_H

PARAM_FUNC_BLOCK_DECLARE(net_mac_addr, 6)
PARAM_FUNC_BLOCK_DECLARE(net_ip_addr, 4)
PARAM_FUNC_BLOCK_DECLARE(net_ip_mask, 4)
PARAM_FUNC_BLOCK_DECLARE(net_ip_gw, 4)
PARAM_FUNC_BYTE_DECLARE(net_dev)
PARAM_FUNC_BYTE_DECLARE(blk_dev)
PARAM_FUNC_WORD_DECLARE(net_mtu)

#endif
