#ifndef PAMELA_ERR_H
#define PAMELA_ERR_H

#define PAMELA_OK                        0
#define PAMELA_ERROR_NO_MEM              -1
#define PAMELA_ERROR_INIT_ENV            -2
#define PAMELA_ERROR_INIT_PROTO          -3
#define PAMELA_ERROR_PROTO_RAK_INVALID   -4
#define PAMELA_ERROR_PROTO_TIMEOUT       -5
#define PAMELA_ERROR_PROTO_DEV_BUSY      -6
#define PAMELA_ERROR_PROTO_ODD_SIZE      -7
#define PAMELA_ERROR_NO_FREE_CHANNEL     -8
#define PAMELA_ERROR_DEV_OPEN_FAILED     -9
#define PAMELA_ERROR_CHANNEL_NOT_OPEN    -10
#define PAMELA_ERROR_CHANNEL_EOS         -11
#define PAMELA_ERROR_CHANNEL_ERROR       -12
#define PAMELA_ERROR_CHANNEL_STATE       -13
#define PAMELA_ERROR_MSG_TOO_LARGE       -14
#define PAMELA_ERROR_CHANNEL_NOT_FOUND   -15
#define PAMELA_ERROR_ALREADY_READING     -16
#define PAMELA_ERROR_ALREADY_WRITING     -17
#define PAMELA_ERROR_READ_FAILED         -18
#define PAMELA_ERROR_WRITE_FAILED        -19
#define PAMELA_ERROR_UNKNOWN             -99

#endif

