#ifndef PAMELA_ERROR_H
#define PAMELA_ERROR_H

#define PAMELA_OK                        0
#define PAMELA_ERROR_NO_MEM              -1
#define PAMELA_ERROR_INIT_ENV            -2
#define PAMELA_ERROR_INIT_PROTO          -3
#define PAMELA_ERROR_PROTO_RAK_INVALID   -4
#define PAMELA_ERROR_PROTO_TIMEOUT       -5
#define PAMELA_ERROR_PROTO_DEV_BUSY      -6
#define PAMELA_ERROR_PROTO_ODD_SIZE      -7
#define PAMELA_ERROR_NO_FREE_CHANNEL     -8
#define PAMELA_ERROR_DEV_OPEN_FAILED     -9
#define PAMELA_ERROR_CHANNEL_NOT_ACTIVE  -10
#define PAMELA_ERROR_CHANNEL_STATE       -12
#define PAMELA_ERROR_MSG_TOO_LARGE       -13
#define PAMELA_ERROR_CHANNEL_NOT_FOUND   -14
#define PAMELA_ERROR_ALREADY_READING     -15
#define PAMELA_ERROR_ALREADY_WRITING     -16
#define PAMELA_ERROR_READ_FAILED         -17
#define PAMELA_ERROR_WRITE_FAILED        -18
#define PAMELA_ERROR_INVALID_MTU         -19
#define PAMELA_ERROR_ODD_MTU             -20
#define PAMELA_ERROR_NO_HANDLE           -21
#define PAMELA_ERROR_UNKNOWN             -99

#define PAMELA_ERROR_CUSTOM              -30

#endif

