include $(CONFIG_MAKE_FILE)

OBJDIR=$(BUILD_DIR)/obj

ASM_SUFFIX?=s
COBJ = $(patsubst %.c,$(OBJDIR)/%.o,$(CSRC))
AOBJ = $(patsubst %.$(ASM_SUFFIX),$(OBJDIR)/%.o,$(ASRC))
OBJ = $(AOBJ) $(COBJ)

# setup CFLAGS
CFLAGS_INCLUDES = -I$(BUILD_DIR) $(patsubst %,-I%,$(INCLUDES))
CFLAGS_DEBUG = -g

CFLAGS = $(CFLAGS_COMMON) $(CFLAGS_INCLUDES) $(CFLAGS_ARCH) $(CFLAGS_DEBUG)

# setup ASFLAGS
ASFLAGS = $(ASFLAGS_COMMON) $(CFLAGS_INCLUDES) $(ASFLAGS_ARCH)

LDFLAGS_DEBUG = -g
LDFLAGS = $(LDFLAGS_COMMON) $(LDFLAGS_ARCH) $(LDFLAGS_DEBUG)

TARGET ?= target
TARGET_BIN = $(BUILD_DIR)/$(TARGET)
