// handler registers
#define HANDLER_REG_INDEX          (PROTO_REGOFFSET_HANDLER + 0)
#define HANDLER_REG_STATUS_CONTROL (PROTO_REGOFFSET_HANDLER + 1)
#define HANDLER_REG_MTU            (PROTO_REGOFFSET_HANDLER + 2)
#define HANDLER_REGNUM             3
