#include "proto_shared.h"

#define TEST_PAMELA_ACTION_TRIGGER_SIGNAL       (PROTO_ACTION_USER+0)
#define TEST_PAMELA_ACTION_BUSY_LOOP            (PROTO_ACTION_USER+1)

#define TEST_PAMELA_WFUNC_READ_TEST_VALUE       (PROTO_WFUNC_READ_USER+0)
#define TEST_PAMELA_WFUNC_WRITE_TEST_VALUE      (PROTO_WFUNC_WRITE_USER+0)

#define TEST_PAMELA_LFUNC_READ_TEST_VALUE       (PROTO_LFUNC_READ_USER+0)
#define TEST_PAMELA_LFUNC_WRITE_TEST_VALUE      (PROTO_LFUNC_WRITE_USER+0)

#define TEST_PAMELA_LFUNC_SET_STATUS            (PROTO_LFUNC_WRITE_USER+1)

#define TEST_PAMELA_SPI_CHANNEL                 8
#define TEST_PAMELA_NET_CHANNEL                 9
